// generated by stringer -type=KeyID; DO NOT EDIT

package types

import "fmt"

const _KeyID_name = "BeginEndIfThenWhileDoRetFuncVarConstOddWriteWriteLnEndOfKeyWdPlusMinusMultDivLparenRparenEqualLssGtrNotEqLssEqGtrEqCommaPeriodSemicolonAssignEndOfKeySymIDNumNulEndOfTokenLetterDigitColonOthers"

var _KeyID_index = [...]uint8{0, 5, 8, 10, 14, 19, 21, 24, 28, 31, 36, 39, 44, 51, 61, 65, 70, 74, 77, 83, 89, 94, 97, 100, 105, 110, 115, 120, 126, 135, 141, 152, 154, 157, 160, 170, 176, 181, 186, 192}

func (i KeyID) String() string {
	if i < 0 || i >= KeyID(len(_KeyID_index)-1) {
		return fmt.Sprintf("KeyID(%d)", i)
	}
	return _KeyID_name[_KeyID_index[i]:_KeyID_index[i+1]]
}
